name: Bash for Baseline Profile Amender

on:
  workflow_dispatch:

jobs:
  baseline-profile-amender:
    name: Run Bash for Baseline Profile Amender
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@v3.1.0

      # Run bash for baseline profile
      - name: Run Bash for Baseline Profile Amender
        run: |
          ./bash/baseline-profile-amender.sh

      # Create Pull Request
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "Run bash for amending baseline profiles"
          title: "Bash: Amend Baseline Profiles"
          delete-branch: true
          reviewers: skydoves
          branch: actions/baseline-profiles
